# Investigating Correlation: Economic Factors:

### Dependencies

In [72]:
import pandas as pd
import numpy as np
from scipy.stats.stats import pearsonr

### Import population data and create dataframe

In [7]:
filepath = '../../raw/economic_stats/population_by_state_by_year.csv'
csv = pd.read_csv(filepath)
population_df = pd.DataFrame(csv)

In [8]:
population_df.head()

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,4050055,553290,3684097,2356586,29959515,3307618,3291967,669567,605321,...,697101,4894492,17056755,1731223,564798,6216884,4903043,1792548,4904562,453690
1,1991,4099156,570193,3788576,2383144,30470736,3387119,3302895,683080,600870,...,703669,4966587,17398005,1779780,568606,6301217,5025624,1798735,4964343,459260
2,1992,4154014,588736,3915740,2415984,30974659,3495939,3300712,694925,597565,...,712801,5049742,17759738,1836799,572751,6414307,5160757,1806451,5025398,466251
3,1993,4214202,599432,4065440,2456303,31274928,3613734,3309175,706378,595301,...,722159,5137584,18161612,1898404,577748,6509630,5278842,1817539,5084889,473081
4,1994,4260229,603308,4245089,2494019,31484435,3724168,3316121,717545,589239,...,730790,5231438,18564062,1960446,583836,6593139,5375161,1820421,5133678,480283

### Import number of school shootings per year csv and create DataFrame

In [13]:
filepath2 = '../../output/sparse_school_shootings_per_state_per_year.csv'
csv2 = pd.read_csv(filepath2)
shootings_df = pd.DataFrame(csv2)

# name year column (currently unnamed)
shootings_df = shootings_df.rename(columns={'Unnamed: 0': 'Year'})

In [15]:
shootings_df.head(30)

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
1,1991,0,0,0,0,1,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
2,1992,1,0,1,0,2,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
3,1993,0,0,0,0,4,0,1,1,1,...,0,0,4,1,0,0,1,0,1,1
4,1994,0,0,0,0,5,0,0,0,0,...,0,1,1,0,0,0,3,0,0,0
5,1995,0,0,0,0,2,0,0,0,1,...,0,2,1,0,0,0,1,0,0,0
6,1996,1,0,0,1,5,0,0,0,2,...,0,1,1,0,0,0,1,0,0,0
7,1997,0,1,0,1,2,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8,1998,0,0,0,2,5,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
9,1999,0,0,0,0,1,1,0,0,0,...,0,0,2,0,0,0,0,0,0,0
10,2000,0,0,1,1,2,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
11,2001,0,0,0,0,4,0,0,0,0,...,0,0,3,1,0,0,2,0,0,0
12,2002,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0
13,2003,0,0,0,0,1,0,0,0,1,...,0,0,3,0,0,0,0,0,0,0
14,2004,0,0,0,0,0,0,0,0,2,...,0,1,0,1,0,0,2,0,0,0
15,2005,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
16,2006,1,0,0,0,2,1,0,0,0,...,0,0,2,0,1,0,0,1,1,0
17,2007,0,0,0,0,2,0,0,1,0,...,0,1,1,0,0,1,2,0,0,0
18,2008,1,0,1,3,3,0,0,0,1,...,0,3,1,1,0,0,1,0,0,0
19,2009,0,0,0,0,5,0,1,1,0,...,0,0,3,0,0,3,0,0,1,0
20,2010,4,0,1,0,3,2,0,0,0,...,0,2,1,0,0,1,1,0,1,0
21,2011,1,0,0,0,4,0,0,0,0,...,0,1,3,0,0,1,0,0,0,0
22,2012,1,0,0,0,2,0,1,0,0,...,0,1,2,0,0,0,1,0,0,0
23,2013,1,0,2,0,3,1,0,0,0,...,0,0,1,0,0,2,0,0,0,0
24,2014,0,0,0,0,3,0,1,0,0,...,0,2,0,0,0,0,2,0,0,0
25,2015,0,0,1,0,2,0,0,0,0,...,1,1,1,0,0,0,1,0,1,0
26,2016,1,0,1,0,2,0,0,0,0,...,0,0,1,2,0,0,0,0,1,0
27,2017,0,0,0,0,3,0,0,0,0,...,0,0,1,0,0,0,2,0,0,0
28,2018,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [17]:
population_df.head(30)

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,4050055,553290,3684097,2356586,29959515,3307618,3291967,669567,605321,...,697101,4894492,17056755,1731223,564798,6216884,4903043,1792548,4904562,453690
1,1991,4099156,570193,3788576,2383144,30470736,3387119,3302895,683080,600870,...,703669,4966587,17398005,1779780,568606,6301217,5025624,1798735,4964343,459260
2,1992,4154014,588736,3915740,2415984,30974659,3495939,3300712,694925,597565,...,712801,5049742,17759738,1836799,572751,6414307,5160757,1806451,5025398,466251
3,1993,4214202,599432,4065440,2456303,31274928,3613734,3309175,706378,595301,...,722159,5137584,18161612,1898404,577748,6509630,5278842,1817539,5084889,473081
4,1994,4260229,603308,4245089,2494019,31484435,3724168,3316121,717545,589239,...,730790,5231438,18564062,1960446,583836,6593139,5375161,1820421,5133678,480283
5,1995,4296800,604412,4432499,2535399,31696582,3826653,3324144,729734,580517,...,737925,5326936,18958751,2014177,589002,6670693,5481027,1823700,5184836,485160
6,1996,4331102,608569,4586940,2572109,32018834,3919972,3336685,740977,572377,...,742213,5416643,19340342,2067976,593701,6750884,5569753,1822808,5229986,488167
7,1997,4367935,612968,4736990,2601090,32486010,4018293,3349348,751487,567736,...,744223,5499233,19740317,2119784,597239,6829183,5674747,1819113,5266213,489451
8,1998,4404701,619932,4883342,2626289,32987675,4116639,3365352,763335,565230,...,746058,5570045,20157531,2165960,600416,6900918,5769562,1815609,5297672,490787
9,1999,4430141,624779,5023823,2651860,33499204,4226018,3386401,774990,570213,...,750412,5638706,20558220,2203482,604683,7000174,5842564,1811799,5332666,491780
10,2000,4452173,627963,5160586,2678588,33987977,4326921,3411777,786373,572046,...,755844,5703719,20944499,2244502,609618,7105817,5910512,1807021,5373999,494300
11,2001,4467634,633714,5273477,2691571,34479458,4425687,3432835,795699,574504,...,757972,5750789,21319622,2283715,612223,7198362,5985722,1801481,5406835,494657
12,2002,4480089,642337,5396255,2705927,34871843,4490406,3458749,806169,573158,...,760020,5795918,21690325,2324815,615442,7286873,6052349,1805414,5445162,500017
13,2003,4503491,648414,5510364,2724816,35253159,4528732,3484336,818003,568502,...,763729,5847812,22030931,2360137,617858,7366977,6104115,1812295,5479203,503453
14,2004,4530729,659286,5652404,2749686,35574576,4575013,3496094,830803,567754,...,770396,5910809,22394023,2401580,619920,7475575,6178645,1816438,5514026,509106
15,2005,4569805,666946,5839077,2781097,35827943,4631888,3506956,845150,567136,...,775493,5991057,22778123,2457719,621215,7577105,6257305,1820492,5546166,514157
16,2006,4628981,675302,6029141,2821761,36021202,4720423,3517460,859268,570681,...,783033,6088766,23359580,2525507,622892,7673725,6370753,1827912,5577655,522667
17,2007,4672840,680300,6167681,2848650,36250311,4803868,3527270,871749,574404,...,791623,6175727,23831983,2597746,623481,7751000,6461587,1834052,5610775,534876
18,2008,4718206,687455,6280362,2874554,36604337,4889730,3545579,883874,580236,...,799124,6247411,24309039,2663029,624151,7833496,6562231,1840310,5640996,546043
19,2009,4757938,698895,6343154,2896843,36961229,4972195,3561807,891730,592228,...,807067,6306019,24801761,2723421,624817,7925937,6667426,1847775,5669264,559851
20,2010,4785579,714015,6407002,2921737,37327690,5048029,3580171,899712,605040,...,816227,6355882,25241648,2775260,625842,8025206,6741386,1854315,5690403,564376
21,2011,4798649,722259,6465488,2938640,37672654,5116411,3591927,907884,620336,...,823338,6396281,25644424,2815430,626210,8107548,6819155,1854891,5705812,567602
22,2012,4813946,730825,6544211,2949208,38019006,5186330,3597705,916868,635630,...,832576,6450632,26078327,2854222,625606,8188656,6890899,1855360,5721075,576608
23,2013,4827660,736760,6616124,2956780,38347383,5262556,3602470,925114,650114,...,842513,6490795,26479279,2899961,626044,8261689,6963410,1852333,5736673,582341
24,2014,4840037,736759,6706435,2964800,38701278,5342311,3600188,934805,660797,...,849455,6540007,26954436,2938671,625665,8316902,7046931,1847624,5751272,583334
25,2015,4850858,737979,6802262,2975626,39032444,5440445,3593862,944107,672736,...,854036,6590726,27454880,2984917,624455,8366767,7152818,1839767,5759744,586102
26,2016,4860545,741522,6908642,2988231,39296476,5530105,3587685,952698,684336,...,861542,6649404,27904862,3044321,623354,8414380,7280934,1828637,5772917,584910
27,2017,4874747,739795,7016270,3004279,39536653,5607154,3588184,961939,693972,...,869666,6715984,28304596,3101833,623657,8470020,7405743,1815857,5795483,579315

### Import unemployment rate csv

In [20]:
filepath3 = '../../raw/economic_stats/unemployment_by_state.csv'
csv3 = pd.read_csv(filepath3)
unemployment_rate_df = pd.DataFrame(csv3)

In [21]:
unemployment_rate_df.head(30)

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,6.8,7.2,5.3,6.9,5.8,5.2,5.1,4.7,6.3,...,3.8,5.3,6.3,4.4,5.0,4.5,5.2,8.5,4.4,5.3
1,1991,7.3,8.5,5.9,7.4,7.7,5.3,6.5,6.2,7.8,...,3.5,6.8,6.9,4.7,6.6,5.9,6.3,10.6,5.5,5.2
2,1992,7.6,8.9,7.5,7.1,9.3,6.0,7.6,5.4,8.6,...,3.3,6.5,7.6,4.8,6.1,6.3,7.3,11.3,5.1,5.6
3,1993,7.3,7.7,6.4,6.1,9.5,5.3,6.6,5.1,8.5,...,3.4,5.8,7.2,4.1,5.2,5.2,7.3,10.6,4.8,5.3
4,1994,6.2,7.6,6.1,5.4,8.6,4.2,5.6,4.8,8.0,...,3.3,4.8,6.5,3.8,4.6,4.9,6.6,8.8,4.5,5.0
5,1995,6.0,7.3,5.3,4.8,7.9,4.0,5.5,4.3,8.8,...,3.0,5.2,6.1,3.5,4.3,4.5,6.4,7.9,3.8,4.8
6,1996,5.2,7.6,5.6,5.3,7.3,4.2,5.5,5.1,8.4,...,3.2,5.2,5.7,3.4,4.3,4.4,6.1,7.5,3.6,4.9
7,1997,5.0,7.1,4.6,5.2,6.4,3.5,5.0,4.0,8.0,...,2.9,5.3,5.3,3.2,3.9,3.8,4.9,6.9,3.6,4.8
8,1998,4.4,6.3,4.3,5.2,5.9,3.6,3.4,3.7,8.4,...,2.8,4.3,4.9,3.6,3.4,2.9,4.8,6.6,3.4,4.7
9,1999,4.7,6.5,4.4,4.6,5.2,3.1,2.9,3.4,6.4,...,2.7,4.0,4.7,3.5,3.0,2.7,4.9,6.5,3.1,4.6
10,2000,4.6,6.4,4.0,4.3,4.9,2.8,2.4,3.7,5.6,...,2.5,3.9,4.3,3.3,2.8,2.3,5.2,5.5,3.5,3.9
11,2001,5.1,6.4,4.8,5.0,5.4,3.8,3.1,3.5,6.3,...,3.1,4.6,5.0,4.4,3.3,3.2,6.3,5.0,4.5,3.8
12,2002,5.9,7.3,6.1,5.5,6.7,5.5,4.3,4.0,6.4,...,3.2,5.2,6.4,5.8,4.0,4.2,7.4,5.9,5.4,4.0
13,2003,6.0,7.8,5.7,5.9,6.8,6.0,5.4,4.3,6.8,...,3.5,5.6,6.7,5.6,4.3,4.1,7.4,6.0,5.7,4.3
14,2004,5.7,7.5,5.0,5.7,6.2,5.5,5.0,4.0,7.8,...,3.7,5.3,5.9,5.0,3.7,3.8,6.3,5.3,5.0,3.8
15,2005,4.5,6.9,4.7,5.2,5.4,5.0,4.9,4.1,6.4,...,3.8,5.6,5.4,4.1,3.5,3.6,5.6,5.1,4.7,3.6
16,2006,4.0,6.6,4.2,5.2,4.9,4.3,4.3,3.6,5.8,...,3.1,5.2,4.9,3.0,3.7,3.1,5.0,4.9,4.7,3.2
17,2007,4.0,6.3,3.9,5.3,5.4,3.7,4.5,3.4,5.5,...,2.8,4.7,4.3,2.6,4.0,3.0,4.7,4.6,4.9,2.8
18,2008,5.7,6.7,6.2,5.5,7.3,4.8,5.7,4.9,6.5,...,3.1,6.6,4.8,3.6,4.7,3.9,5.4,4.3,4.9,3.1
19,2009,11.0,7.7,9.9,7.8,11.2,7.3,7.9,8.3,9.3,...,4.9,10.5,7.6,7.3,6.6,6.7,9.2,7.7,8.6,6.3
20,2010,10.5,7.9,10.4,8.2,12.2,8.7,9.1,8.4,9.4,...,5.0,9.7,8.1,7.8,6.1,7.1,10.0,8.7,8.7,6.4
21,2011,9.6,7.6,9.5,8.3,11.7,8.4,8.8,7.5,10.2,...,4.7,9.0,7.8,6.7,5.5,6.6,9.3,8.1,7.8,5.8
22,2012,8.0,7.1,8.3,7.6,10.4,7.9,8.3,7.2,9.0,...,4.3,7.8,6.7,5.4,5.0,6.0,8.1,7.5,7.0,5.3
23,2013,7.2,6.9,7.7,7.3,8.9,6.8,7.8,6.7,8.5,...,3.8,7.8,6.2,4.6,4.4,5.7,7.0,6.7,6.7,4.7
24,2014,6.8,6.9,6.8,6.1,7.5,5.0,6.6,5.7,7.8,...,3.4,6.5,5.1,3.8,4.0,5.2,6.1,6.6,5.4,4.1
25,2015,6.1,6.5,6.1,5.2,6.2,3.9,5.6,4.9,6.9,...,3.1,5.8,4.5,3.5,3.7,4.4,5.7,6.7,4.6,4.2

### Cut off population and shooting dataframes to 2015

In [49]:
shootings_df = shootings_df[shootings_df['Year'] != 2018]
shootings_df = shootings_df[shootings_df['Year'] != 2017]
shootings_df = shootings_df[shootings_df['Year'] != 2016]

shootings_df = shootings_df.replace(np.NaN, 0)

population_df = population_df[population_df['Year'] != 2018]
population_df = population_df[population_df['Year'] != 2017]
population_df = population_df[population_df['Year'] != 2016]

population_df = population_df.replace(np.NaN, 0)

### Divide number of school shootings by population to get school shootings per capita

In [50]:
shootings_percap_df = shootings_df / population_df

### Calculate correlation between a state's school shootings per capita and its unemployment rate

In [51]:
np.corrcoef(shootings_percap_df['Illinois'], unemployment_rate_df['Illinois'])

array([[ 1.        ,  0.40333739],
       [ 0.40333739,  1.        ]])

In [74]:
# Check correlations between school shootings per capita and unemployment rate
for element in population_df.columns.tolist()[1:]:
    print(element, 'Pearson correlation: ', pearsonr(shootings_percap_df[element], unemployment_rate_df[element]))

Alabama Pearson correlation:  (0.48052633159265395, 0.012964214604823363)
Alaska Pearson correlation:  (-0.030337336440447314, 0.88304022457666542)
Arizona Pearson correlation:  (0.25964971286457772, 0.20021154382637354)
Arkansas Pearson correlation:  (-0.30338071804532923, 0.13190510312775255)
California Pearson correlation:  (0.3886248428432128, 0.049756261054039332)
Colorado Pearson correlation:  (0.2629172586892074, 0.19440466733398512)
Connecticut Pearson correlation:  (0.40140860759274666, 0.042101346276298621)
Delaware Pearson correlation:  (0.12452808735169137, 0.54444211468636405)
District of Columbia Pearson correlation:  (0.11076163995334523, 0.59012038291908064)
Florida Pearson correlation:  (-0.0087096959929334229, 0.96631742415530519)
Georgia Pearson correlation:  (0.076071343629587604, 0.71186808998430129)
Hawaii Pearson correlation:  (0.30273188858894251, 0.13277491127378371)
Idaho Pearson correlation:  (-0.097133176534598784, 0.63689522109009844)
Illinois Pearson correlation:  (0.40333739183147094, 0.041032185377727952)
Indiana Pearson correlation:  (0.033143735212776027, 0.87230393830535202)
Iowa Pearson correlation:  (0.26099902068978104, 0.1977994478993689)
Kansas Pearson correlation:  (-0.08429139000332958, 0.68224969539171387)
Kentucky Pearson correlation:  (0.22766436998619838, 0.26333645258805155)
Louisiana Pearson correlation:  (0.081002239478249735, 0.69404910371113093)
Maine Pearson correlation:  (-0.028069178610689478, 0.89173219884865085)
Maryland Pearson correlation:  (0.11069624957787719, 0.59034123506592162)
Massachusetts Pearson correlation:  (0.51863830996299098, 0.0066364519869999182)
Michigan Pearson correlation:  (0.29550489234555233, 0.14274571820284365)
Minnesota Pearson correlation:  (0.020554968847261684, 0.92060970109663165)
Mississippi Pearson correlation:  (0.0069720861942146857, 0.97303450279062276)
Missouri Pearson correlation:  (-0.12006242601701554, 0.55907785046275904)
Montana Pearson correlation:  (-0.030066567058836202, 0.88407718701917526)
Nebraska Pearson correlation:  (0.13384071620598278, 0.5145074802647891)
Nevada Pearson correlation:  (-0.16100757958430331, 0.43201338722277749)
New Hampshire Pearson correlation:  (0.15602481086188086, 0.44658190904389639)
New Jersey Pearson correlation:  (-0.050448666073247175, 0.80665541570947297)
New Mexico Pearson correlation:  (-0.021271310449276899, 0.91785196164920291)
New York Pearson correlation:  (0.33658959678677186, 0.092698012721581582)
North Carolina Pearson correlation:  (0.23584594227228139, 0.24609284469301251)
North Dakota Pearson correlation:  (nan, 1.0)
Ohio Pearson correlation:  (0.011956763053157517, 0.95377157570932769)
Oklahoma Pearson correlation:  (-0.40157269084956632, 0.04200954261950713)
Oregon Pearson correlation:  (-0.28831122914256757, 0.15319355702494636)
Pennsylvania Pearson correlation:  (-0.2326902195506127, 0.25265386433085441)
Rhode Island Pearson correlation:  (nan, 1.0)
South Carolina Pearson correlation:  (0.18847521320074401, 0.35648932754777596)
South Dakota Pearson correlation:  (-0.11149724688573989, 0.58763837204332292)
Tennessee Pearson correlation:  (0.038689117253959127, 0.85115560966917592)
Texas Pearson correlation:  (0.48013857744160532, 0.013047970106330856)
Utah Pearson correlation:  (-0.052470098143854046, 0.79906066608371051)
Vermont Pearson correlation:  (-0.14489333522704659, 0.48005216331973266)
Virginia Pearson correlation:  (0.37336686088273841, 0.060276487999308279)
Washington Pearson correlation:  (-0.069245975437986315, 0.73677646014604192)
West Virginia Pearson correlation:  (-0.23468241578088139, 0.24849877783000499)
Wisconsin Pearson correlation:  (0.35206532559242965, 0.077753916522786196)
Wyoming Pearson correlation:  (0.15362835115484369, 0.45368063880881027)

In [70]:
for index in range(0, 26):
    print(unemployment_rate_df.iat[index, 0], ' corr: ', np.corrcoef(shootings_percap_df.loc[index], unemployment_rate_df.loc[index]))
    print('\n\n-------------\n-----------------\n')

1990  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1991  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1992  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1993  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1994  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1995  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1996  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1997  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1998  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

1999  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2000  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2001  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2002  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2003  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2004  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2005  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2006  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2007  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2008  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2009  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2010  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2011  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2012  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2013  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2014  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

2015  corr:  [[ nan  nan]
 [ nan   1.]]


-------------
-----------------

In [61]:
shootings_percap_df[: 1]

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Year
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.043113e-07,5.862780e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [69]:
np.corrcoef(shootings_percap_df[0], unemployment_rate_df[0])

KeyError: 0