# Investigating Correlation: Economic Factors:

### Dependencies

In [1]:
import pandas as pd
import numpy as np
from scipy.stats.stats import pearsonr

### Import population data and create dataframe

In [2]:
filepath = '../../raw/economic_stats/population_by_state_by_year.csv'
csv = pd.read_csv(filepath)
population_df = pd.DataFrame(csv)

In [3]:
population_df.head()

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,4050055,553290,3684097,2356586,29959515,3307618,3291967,669567,605321,...,697101,4894492,17056755,1731223,564798,6216884,4903043,1792548,4904562,453690
1,1991,4099156,570193,3788576,2383144,30470736,3387119,3302895,683080,600870,...,703669,4966587,17398005,1779780,568606,6301217,5025624,1798735,4964343,459260
2,1992,4154014,588736,3915740,2415984,30974659,3495939,3300712,694925,597565,...,712801,5049742,17759738,1836799,572751,6414307,5160757,1806451,5025398,466251
3,1993,4214202,599432,4065440,2456303,31274928,3613734,3309175,706378,595301,...,722159,5137584,18161612,1898404,577748,6509630,5278842,1817539,5084889,473081
4,1994,4260229,603308,4245089,2494019,31484435,3724168,3316121,717545,589239,...,730790,5231438,18564062,1960446,583836,6593139,5375161,1820421,5133678,480283

### Import number of school shootings per year csv and create DataFrame

In [4]:
filepath2 = '../../output/sparse_school_shootings_per_state_per_year.csv'
csv2 = pd.read_csv(filepath2)
shootings_df = pd.DataFrame(csv2)

# name year column (currently unnamed)
shootings_df = shootings_df.rename(columns={'Unnamed: 0': 'Year'})

In [5]:
shootings_df.head(30)

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
1,1991,0,0,0,0,1,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
2,1992,1,0,1,0,2,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
3,1993,0,0,0,0,4,0,1,1,1,...,0,0,4,1,0,0,1,0,1,1
4,1994,0,0,0,0,5,0,0,0,0,...,0,1,1,0,0,0,3,0,0,0
5,1995,0,0,0,0,2,0,0,0,1,...,0,2,1,0,0,0,1,0,0,0
6,1996,1,0,0,1,5,0,0,0,2,...,0,1,1,0,0,0,1,0,0,0
7,1997,0,1,0,1,2,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8,1998,0,0,0,2,5,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
9,1999,0,0,0,0,1,1,0,0,0,...,0,0,2,0,0,0,0,0,0,0
10,2000,0,0,1,1,2,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
11,2001,0,0,0,0,4,0,0,0,0,...,0,0,3,1,0,0,2,0,0,0
12,2002,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0
13,2003,0,0,0,0,1,0,0,0,1,...,0,0,3,0,0,0,0,0,0,0
14,2004,0,0,0,0,0,0,0,0,2,...,0,1,0,1,0,0,2,0,0,0
15,2005,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
16,2006,1,0,0,0,2,1,0,0,0,...,0,0,2,0,1,0,0,1,1,0
17,2007,0,0,0,0,2,0,0,1,0,...,0,1,1,0,0,1,2,0,0,0
18,2008,1,0,1,3,3,0,0,0,1,...,0,3,1,1,0,0,1,0,0,0
19,2009,0,0,0,0,5,0,1,1,0,...,0,0,3,0,0,3,0,0,1,0
20,2010,4,0,1,0,3,2,0,0,0,...,0,2,1,0,0,1,1,0,1,0
21,2011,1,0,0,0,4,0,0,0,0,...,0,1,3,0,0,1,0,0,0,0
22,2012,1,0,0,0,2,0,1,0,0,...,0,1,2,0,0,0,1,0,0,0
23,2013,1,0,2,0,3,1,0,0,0,...,0,0,1,0,0,2,0,0,0,0
24,2014,0,0,0,0,3,0,1,0,0,...,0,2,0,0,0,0,2,0,0,0
25,2015,0,0,1,0,2,0,0,0,0,...,1,1,1,0,0,0,1,0,1,0
26,2016,1,0,1,0,2,0,0,0,0,...,0,0,1,2,0,0,0,0,1,0
27,2017,0,0,0,0,3,0,0,0,0,...,0,0,1,0,0,0,2,0,0,0
28,2018,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [6]:
population_df.head(30)

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,4050055,553290,3684097,2356586,29959515,3307618,3291967,669567,605321,...,697101,4894492,17056755,1731223,564798,6216884,4903043,1792548,4904562,453690
1,1991,4099156,570193,3788576,2383144,30470736,3387119,3302895,683080,600870,...,703669,4966587,17398005,1779780,568606,6301217,5025624,1798735,4964343,459260
2,1992,4154014,588736,3915740,2415984,30974659,3495939,3300712,694925,597565,...,712801,5049742,17759738,1836799,572751,6414307,5160757,1806451,5025398,466251
3,1993,4214202,599432,4065440,2456303,31274928,3613734,3309175,706378,595301,...,722159,5137584,18161612,1898404,577748,6509630,5278842,1817539,5084889,473081
4,1994,4260229,603308,4245089,2494019,31484435,3724168,3316121,717545,589239,...,730790,5231438,18564062,1960446,583836,6593139,5375161,1820421,5133678,480283
5,1995,4296800,604412,4432499,2535399,31696582,3826653,3324144,729734,580517,...,737925,5326936,18958751,2014177,589002,6670693,5481027,1823700,5184836,485160
6,1996,4331102,608569,4586940,2572109,32018834,3919972,3336685,740977,572377,...,742213,5416643,19340342,2067976,593701,6750884,5569753,1822808,5229986,488167
7,1997,4367935,612968,4736990,2601090,32486010,4018293,3349348,751487,567736,...,744223,5499233,19740317,2119784,597239,6829183,5674747,1819113,5266213,489451
8,1998,4404701,619932,4883342,2626289,32987675,4116639,3365352,763335,565230,...,746058,5570045,20157531,2165960,600416,6900918,5769562,1815609,5297672,490787
9,1999,4430141,624779,5023823,2651860,33499204,4226018,3386401,774990,570213,...,750412,5638706,20558220,2203482,604683,7000174,5842564,1811799,5332666,491780
10,2000,4452173,627963,5160586,2678588,33987977,4326921,3411777,786373,572046,...,755844,5703719,20944499,2244502,609618,7105817,5910512,1807021,5373999,494300
11,2001,4467634,633714,5273477,2691571,34479458,4425687,3432835,795699,574504,...,757972,5750789,21319622,2283715,612223,7198362,5985722,1801481,5406835,494657
12,2002,4480089,642337,5396255,2705927,34871843,4490406,3458749,806169,573158,...,760020,5795918,21690325,2324815,615442,7286873,6052349,1805414,5445162,500017
13,2003,4503491,648414,5510364,2724816,35253159,4528732,3484336,818003,568502,...,763729,5847812,22030931,2360137,617858,7366977,6104115,1812295,5479203,503453
14,2004,4530729,659286,5652404,2749686,35574576,4575013,3496094,830803,567754,...,770396,5910809,22394023,2401580,619920,7475575,6178645,1816438,5514026,509106
15,2005,4569805,666946,5839077,2781097,35827943,4631888,3506956,845150,567136,...,775493,5991057,22778123,2457719,621215,7577105,6257305,1820492,5546166,514157
16,2006,4628981,675302,6029141,2821761,36021202,4720423,3517460,859268,570681,...,783033,6088766,23359580,2525507,622892,7673725,6370753,1827912,5577655,522667
17,2007,4672840,680300,6167681,2848650,36250311,4803868,3527270,871749,574404,...,791623,6175727,23831983,2597746,623481,7751000,6461587,1834052,5610775,534876
18,2008,4718206,687455,6280362,2874554,36604337,4889730,3545579,883874,580236,...,799124,6247411,24309039,2663029,624151,7833496,6562231,1840310,5640996,546043
19,2009,4757938,698895,6343154,2896843,36961229,4972195,3561807,891730,592228,...,807067,6306019,24801761,2723421,624817,7925937,6667426,1847775,5669264,559851
20,2010,4785579,714015,6407002,2921737,37327690,5048029,3580171,899712,605040,...,816227,6355882,25241648,2775260,625842,8025206,6741386,1854315,5690403,564376
21,2011,4798649,722259,6465488,2938640,37672654,5116411,3591927,907884,620336,...,823338,6396281,25644424,2815430,626210,8107548,6819155,1854891,5705812,567602
22,2012,4813946,730825,6544211,2949208,38019006,5186330,3597705,916868,635630,...,832576,6450632,26078327,2854222,625606,8188656,6890899,1855360,5721075,576608
23,2013,4827660,736760,6616124,2956780,38347383,5262556,3602470,925114,650114,...,842513,6490795,26479279,2899961,626044,8261689,6963410,1852333,5736673,582341
24,2014,4840037,736759,6706435,2964800,38701278,5342311,3600188,934805,660797,...,849455,6540007,26954436,2938671,625665,8316902,7046931,1847624,5751272,583334
25,2015,4850858,737979,6802262,2975626,39032444,5440445,3593862,944107,672736,...,854036,6590726,27454880,2984917,624455,8366767,7152818,1839767,5759744,586102
26,2016,4860545,741522,6908642,2988231,39296476,5530105,3587685,952698,684336,...,861542,6649404,27904862,3044321,623354,8414380,7280934,1828637,5772917,584910
27,2017,4874747,739795,7016270,3004279,39536653,5607154,3588184,961939,693972,...,869666,6715984,28304596,3101833,623657,8470020,7405743,1815857,5795483,579315

### Import unemployment rate csv

In [7]:
filepath3 = '../../raw/economic_stats/unemployment_by_state.csv'
csv3 = pd.read_csv(filepath3)
unemployment_rate_df = pd.DataFrame(csv3)

In [8]:
unemployment_rate_df.head(30)

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,6.8,7.2,5.3,6.9,5.8,5.2,5.1,4.7,6.3,...,3.8,5.3,6.3,4.4,5.0,4.5,5.2,8.5,4.4,5.3
1,1991,7.3,8.5,5.9,7.4,7.7,5.3,6.5,6.2,7.8,...,3.5,6.8,6.9,4.7,6.6,5.9,6.3,10.6,5.5,5.2
2,1992,7.6,8.9,7.5,7.1,9.3,6.0,7.6,5.4,8.6,...,3.3,6.5,7.6,4.8,6.1,6.3,7.3,11.3,5.1,5.6
3,1993,7.3,7.7,6.4,6.1,9.5,5.3,6.6,5.1,8.5,...,3.4,5.8,7.2,4.1,5.2,5.2,7.3,10.6,4.8,5.3
4,1994,6.2,7.6,6.1,5.4,8.6,4.2,5.6,4.8,8.0,...,3.3,4.8,6.5,3.8,4.6,4.9,6.6,8.8,4.5,5.0
5,1995,6.0,7.3,5.3,4.8,7.9,4.0,5.5,4.3,8.8,...,3.0,5.2,6.1,3.5,4.3,4.5,6.4,7.9,3.8,4.8
6,1996,5.2,7.6,5.6,5.3,7.3,4.2,5.5,5.1,8.4,...,3.2,5.2,5.7,3.4,4.3,4.4,6.1,7.5,3.6,4.9
7,1997,5.0,7.1,4.6,5.2,6.4,3.5,5.0,4.0,8.0,...,2.9,5.3,5.3,3.2,3.9,3.8,4.9,6.9,3.6,4.8
8,1998,4.4,6.3,4.3,5.2,5.9,3.6,3.4,3.7,8.4,...,2.8,4.3,4.9,3.6,3.4,2.9,4.8,6.6,3.4,4.7
9,1999,4.7,6.5,4.4,4.6,5.2,3.1,2.9,3.4,6.4,...,2.7,4.0,4.7,3.5,3.0,2.7,4.9,6.5,3.1,4.6
10,2000,4.6,6.4,4.0,4.3,4.9,2.8,2.4,3.7,5.6,...,2.5,3.9,4.3,3.3,2.8,2.3,5.2,5.5,3.5,3.9
11,2001,5.1,6.4,4.8,5.0,5.4,3.8,3.1,3.5,6.3,...,3.1,4.6,5.0,4.4,3.3,3.2,6.3,5.0,4.5,3.8
12,2002,5.9,7.3,6.1,5.5,6.7,5.5,4.3,4.0,6.4,...,3.2,5.2,6.4,5.8,4.0,4.2,7.4,5.9,5.4,4.0
13,2003,6.0,7.8,5.7,5.9,6.8,6.0,5.4,4.3,6.8,...,3.5,5.6,6.7,5.6,4.3,4.1,7.4,6.0,5.7,4.3
14,2004,5.7,7.5,5.0,5.7,6.2,5.5,5.0,4.0,7.8,...,3.7,5.3,5.9,5.0,3.7,3.8,6.3,5.3,5.0,3.8
15,2005,4.5,6.9,4.7,5.2,5.4,5.0,4.9,4.1,6.4,...,3.8,5.6,5.4,4.1,3.5,3.6,5.6,5.1,4.7,3.6
16,2006,4.0,6.6,4.2,5.2,4.9,4.3,4.3,3.6,5.8,...,3.1,5.2,4.9,3.0,3.7,3.1,5.0,4.9,4.7,3.2
17,2007,4.0,6.3,3.9,5.3,5.4,3.7,4.5,3.4,5.5,...,2.8,4.7,4.3,2.6,4.0,3.0,4.7,4.6,4.9,2.8
18,2008,5.7,6.7,6.2,5.5,7.3,4.8,5.7,4.9,6.5,...,3.1,6.6,4.8,3.6,4.7,3.9,5.4,4.3,4.9,3.1
19,2009,11.0,7.7,9.9,7.8,11.2,7.3,7.9,8.3,9.3,...,4.9,10.5,7.6,7.3,6.6,6.7,9.2,7.7,8.6,6.3
20,2010,10.5,7.9,10.4,8.2,12.2,8.7,9.1,8.4,9.4,...,5.0,9.7,8.1,7.8,6.1,7.1,10.0,8.7,8.7,6.4
21,2011,9.6,7.6,9.5,8.3,11.7,8.4,8.8,7.5,10.2,...,4.7,9.0,7.8,6.7,5.5,6.6,9.3,8.1,7.8,5.8
22,2012,8.0,7.1,8.3,7.6,10.4,7.9,8.3,7.2,9.0,...,4.3,7.8,6.7,5.4,5.0,6.0,8.1,7.5,7.0,5.3
23,2013,7.2,6.9,7.7,7.3,8.9,6.8,7.8,6.7,8.5,...,3.8,7.8,6.2,4.6,4.4,5.7,7.0,6.7,6.7,4.7
24,2014,6.8,6.9,6.8,6.1,7.5,5.0,6.6,5.7,7.8,...,3.4,6.5,5.1,3.8,4.0,5.2,6.1,6.6,5.4,4.1
25,2015,6.1,6.5,6.1,5.2,6.2,3.9,5.6,4.9,6.9,...,3.1,5.8,4.5,3.5,3.7,4.4,5.7,6.7,4.6,4.2

### Cut off population and shooting dataframes to 2015

In [9]:
shootings_df = shootings_df[shootings_df['Year'] != 2018]
shootings_df = shootings_df[shootings_df['Year'] != 2017]
shootings_df = shootings_df[shootings_df['Year'] != 2016]

shootings_df = shootings_df.replace(np.nan, 0)

population_df = population_df[population_df['Year'] != 2018]
population_df = population_df[population_df['Year'] != 2017]
population_df = population_df[population_df['Year'] != 2016]

population_df = population_df.replace(np.nan, 0)

### Divide number of school shootings by population to get school shootings per capita

In [10]:
shootings_percap_df = shootings_df / population_df

### Calculate correlation between a state's school shootings per capita and its unemployment rate

In [11]:
np.corrcoef(shootings_percap_df['Illinois'], unemployment_rate_df['Illinois'])

array([[ 1.        ,  0.40333739],
       [ 0.40333739,  1.        ]])

In [32]:
# Check correlations between school shootings per capita and unemployment rate
for element in population_df.columns.tolist()[1:]:
    print(element, 'Pearson correlation (25 yrs): ', pearsonr(shootings_percap_df[element], unemployment_rate_df[element]))

Alabama Pearson correlation (25 yrs):  (0.48052633159265395, 0.012964214604823363)
Alaska Pearson correlation (25 yrs):  (-0.030337336440447314, 0.88304022457666542)
Arizona Pearson correlation (25 yrs):  (0.25964971286457772, 0.20021154382637354)
Arkansas Pearson correlation (25 yrs):  (-0.30338071804532923, 0.13190510312775255)
California Pearson correlation (25 yrs):  (0.3886248428432128, 0.049756261054039332)
Colorado Pearson correlation (25 yrs):  (0.2629172586892074, 0.19440466733398512)
Connecticut Pearson correlation (25 yrs):  (0.40140860759274666, 0.042101346276298621)
Delaware Pearson correlation (25 yrs):  (0.12452808735169137, 0.54444211468636405)
District of Columbia Pearson correlation (25 yrs):  (0.11076163995334523, 0.59012038291908064)
Florida Pearson correlation (25 yrs):  (-0.0087096959929334229, 0.96631742415530519)
Georgia Pearson correlation (25 yrs):  (0.076071343629587604, 0.71186808998430129)
Hawaii Pearson correlation (25 yrs):  (0.30273188858894251, 0.13277491127378371)
Idaho Pearson correlation (25 yrs):  (-0.097133176534598784, 0.63689522109009844)
Illinois Pearson correlation (25 yrs):  (0.40333739183147094, 0.041032185377727952)
Indiana Pearson correlation (25 yrs):  (0.033143735212776027, 0.87230393830535202)
Iowa Pearson correlation (25 yrs):  (0.26099902068978104, 0.1977994478993689)
Kansas Pearson correlation (25 yrs):  (-0.08429139000332958, 0.68224969539171387)
Kentucky Pearson correlation (25 yrs):  (0.22766436998619838, 0.26333645258805155)
Louisiana Pearson correlation (25 yrs):  (0.081002239478249735, 0.69404910371113093)
Maine Pearson correlation (25 yrs):  (-0.028069178610689478, 0.89173219884865085)
Maryland Pearson correlation (25 yrs):  (0.11069624957787719, 0.59034123506592162)
Massachusetts Pearson correlation (25 yrs):  (0.51863830996299098, 0.0066364519869999182)
Michigan Pearson correlation (25 yrs):  (0.29550489234555233, 0.14274571820284365)
Minnesota Pearson correlation (25 yrs):  (0.020554968847261684, 0.92060970109663165)
Mississippi Pearson correlation (25 yrs):  (0.0069720861942146857, 0.97303450279062276)
Missouri Pearson correlation (25 yrs):  (-0.12006242601701554, 0.55907785046275904)
Montana Pearson correlation (25 yrs):  (-0.030066567058836202, 0.88407718701917526)
Nebraska Pearson correlation (25 yrs):  (0.13384071620598278, 0.5145074802647891)
Nevada Pearson correlation (25 yrs):  (-0.16100757958430331, 0.43201338722277749)
New Hampshire Pearson correlation (25 yrs):  (0.15602481086188086, 0.44658190904389639)
New Jersey Pearson correlation (25 yrs):  (-0.050448666073247175, 0.80665541570947297)
New Mexico Pearson correlation (25 yrs):  (-0.021271310449276899, 0.91785196164920291)
New York Pearson correlation (25 yrs):  (0.33658959678677186, 0.092698012721581582)
North Carolina Pearson correlation (25 yrs):  (0.23584594227228139, 0.24609284469301251)
North Dakota Pearson correlation (25 yrs):  (nan, 1.0)
Ohio Pearson correlation (25 yrs):  (0.011956763053157517, 0.95377157570932769)
Oklahoma Pearson correlation (25 yrs):  (-0.40157269084956632, 0.04200954261950713)
Oregon Pearson correlation (25 yrs):  (-0.28831122914256757, 0.15319355702494636)
Pennsylvania Pearson correlation (25 yrs):  (-0.2326902195506127, 0.25265386433085441)
Rhode Island Pearson correlation (25 yrs):  (nan, 1.0)
South Carolina Pearson correlation (25 yrs):  (0.18847521320074401, 0.35648932754777596)
South Dakota Pearson correlation (25 yrs):  (-0.11149724688573989, 0.58763837204332292)
Tennessee Pearson correlation (25 yrs):  (0.038689117253959127, 0.85115560966917592)
Texas Pearson correlation (25 yrs):  (0.48013857744160532, 0.013047970106330856)
Utah Pearson correlation (25 yrs):  (-0.052470098143854046, 0.79906066608371051)
Vermont Pearson correlation (25 yrs):  (-0.14489333522704659, 0.48005216331973266)
Virginia Pearson correlation (25 yrs):  (0.37336686088273841, 0.060276487999308279)
Washington Pearson correlation (25 yrs):  (-0.069245975437986315, 0.73677646014604192)
West Virginia Pearson correlation (25 yrs):  (-0.23468241578088139, 0.24849877783000499)
Wisconsin Pearson correlation (25 yrs):  (0.35206532559242965, 0.077753916522786196)
Wyoming Pearson correlation (25 yrs):  (0.15362835115484369, 0.45368063880881027)

# Same, but with median household income

### Import median household income dataset

In [33]:
filepath4 = '../../raw/economic_stats/census_median_household_income.csv'
csv4 = pd.read_csv(filepath4)
mhi_df = pd.DataFrame(csv4)

In [37]:
mhi_df.State.max()

2016

In [47]:
mhi_df = mhi_df[mhi_df.State != 2016]
mhi_df = mhi_df.rename(columns={'D.C.': 'District of Columbia'})

In [48]:
mhi_df = mhi_df.replace(np.nan, 0)
mhi_df.head(30)

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1990,23357,39298,29224,22786,33290,30733,38870,30804,27392,...,24571,22592,28228,30142,31098,35073,32112,22137,30711,29460
1,1991,24346,40612,30737,23435,33664,31499,42154,32585,29885,...,24639,24453,27733,28016,29155,36137,33970,23147,31133,29050
2,1992,25808,41802,29358,23882,34903,32484,40841,35678,30247,...,26259,24318,27953,34251,32755,38198,33900,20271,33308,30209
3,1993,25082,42931,30510,23039,34073,34488,39516,36064,27304,...,27737,25102,28727,35786,31065,36433,35655,22421,31766,29442
4,1994,27196,45367,31293,25565,35331,37833,41097,35873,30116,...,29733,28639,30755,35716,35802,37647,33533,23564,35388,33140
5,1995,25991,47954,30863,25814,37009,40706,40243,34928,30748,...,29578,29015,32039,36480,33824,36222,35568,24880,40955,31529
6,1996,30302,52779,31637,27123,38812,40950,42119,39309,31966,...,29526,30790,33072,37038,32358,39211,36676,25247,40001,30953
7,1997,31939,47994,32740,26162,39694,43233,43985,43033,31860,...,29694,30636,35075,42775,35053,42957,44562,27488,39595,33423
8,1998,36266,50692,37090,27665,40934,46599,46508,41458,33433,...,32786,34091,35783,44299,39372,43354,47421,26704,41327,35250
9,1999,36251,51396,36995,29682,43629,48177,50593,46628,38670,...,35828,36522,38688,46050,41584,45693,45473,29297,45667,37248
10,2000,35424,52847,39783,29697,46816,48240,50172,50365,41222,...,36475,34096,38609,47550,39594,47163,42525,29411,45088,39629
11,2001,35160,57363,42704,33339,47262,49397,53347,49602,41169,...,39671,35783,40860,47342,40794,50241,42490,29673,45346,39719
12,2002,37603,52774,39734,32387,47437,48294,53387,49650,39070,...,37873,37030,40149,47861,42999,49631,45183,29359,45903,39763
13,2003,37255,51837,41166,32002,49300,49940,54965,49019,45044,...,39522,37523,39271,49275,43261,54783,47508,32763,46269,42555
14,2004,36629,55063,43846,34984,49222,50886,55100,48049,43451,...,41107,38072,41397,50871,47329,51141,49922,33373,45732,45397
15,2005,37150,55891,45245,36658,51755,50449,56835,51235,44993,...,43151,39406,41422,54813,50704,51914,50646,36445,44650,44718
16,2006,37952,56418,46657,37057,55319,55697,62404,52438,48477,...,45427,40693,43307,54628,51981,57119,54723,38419,51692,47041
17,2007,42212,62993,47215,40795,55734,61141,64141,54589,50783,...,46418,41195,46053,53529,47390,59161,58080,42091,51277,48744
18,2008,44476,63989,46914,39586,57014,60943,64682,50702,55590,...,51600,39702,46490,62537,50706,61985,56631,37994,51200,53337
19,2009,39980,61604,45739,36538,56134,55930,64851,52114,53141,...,45826,40517,47475,58491,52318,60501,60392,40490,51237,52470
20,2010,40933,57848,46896,38587,54283,60233,65998,55214,56928,...,45352,38591,47266,56701,55928,60367,56163,42777,50351,52201
21,2011,42590,57431,48621,41302,53367,58629,65415,54660,55251,...,47223,42279,49047,55493,51862,62616,56850,41821,52058,54509
22,2012,43464,63648,47044,39018,57020,57255,64247,48972,65246,...,49415,42995,51926,58341,55582,64632,62187,43553,53079,57512
23,2013,47320,72472,52611,39376,60794,67912,69291,54091,60057,...,53413,43361,51406,61047,65513,65907,63922,43069,51726,67441
24,2014,42278,67629,49254,44922,60487,60940,70161,57522,68277,...,53053,43716,53875,63383,60708,66155,59068,39552,58080,55690
25,2015,44509,75112,52248,42798,63636,66596,72889,57756,70071,...,55065,47330,56473,66258,59494,61486,67243,42824,55425,60925

In [50]:
# Check correlations between school shootings per capita and unemployment rate
for element in shootings_percap_df.columns.tolist()[:-1]:
    print(element, 'Pearson correlation (25 yrs): ', pearsonr(shootings_percap_df[element], mhi_df[element]))

Alabama Pearson correlation (25 yrs):  (0.258710782969096, 0.20190183464894515)
Alaska Pearson correlation (25 yrs):  (-0.14961730916110219, 0.46569410840604686)
Arizona Pearson correlation (25 yrs):  (0.22495315598526622, 0.26921851648473616)
Arkansas Pearson correlation (25 yrs):  (-0.063429304553010768, 0.75821107770291052)
California Pearson correlation (25 yrs):  (-0.11202551695883464, 0.5858587302256858)
Colorado Pearson correlation (25 yrs):  (0.3199948224271022, 0.11101619791634493)
Connecticut Pearson correlation (25 yrs):  (0.1918810258260468, 0.3477039830130686)
Delaware Pearson correlation (25 yrs):  (0.0039803260820664918, 0.98460369477939524)
District of Columbia Pearson correlation (25 yrs):  (-0.21537652754177866, 0.29066573345004054)
Florida Pearson correlation (25 yrs):  (0.22661244676245951, 0.26560869776321944)
Georgia Pearson correlation (25 yrs):  (0.042715568770485469, 0.83586170466928689)
Hawaii Pearson correlation (25 yrs):  (0.15275971288771742, 0.45626832223973923)
Idaho Pearson correlation (25 yrs):  (-0.10858520369354419, 0.59749021076501085)
Illinois Pearson correlation (25 yrs):  (0.062635262763391875, 0.76115108297945044)
Indiana Pearson correlation (25 yrs):  (0.21139674600531091, 0.29988609227510471)
Iowa Pearson correlation (25 yrs):  (-0.030380674035951311, 0.88287427244545458)
Kansas Pearson correlation (25 yrs):  (-0.26659563842603223, 0.18800728978862558)
Kentucky Pearson correlation (25 yrs):  (0.085007984822711394, 0.67968850595804975)
Louisiana Pearson correlation (25 yrs):  (0.41711532424365705, 0.034006318696649822)
Maine Pearson correlation (25 yrs):  (0.17110705971009549, 0.40329095996651398)
Maryland Pearson correlation (25 yrs):  (0.32648874518077253, 0.10355419562236398)
Massachusetts Pearson correlation (25 yrs):  (-0.16844369774803369, 0.41075941950891159)
Michigan Pearson correlation (25 yrs):  (0.07582174142077179, 0.71277410873808467)
Minnesota Pearson correlation (25 yrs):  (-0.1125415081372461, 0.58412271740613564)
Mississippi Pearson correlation (25 yrs):  (0.047749175295570857, 0.8168242636836105)
Missouri Pearson correlation (25 yrs):  (-0.17685621562308779, 0.38743169185938353)
Montana Pearson correlation (25 yrs):  (-0.2019500058454804, 0.32249400267992462)
Nebraska Pearson correlation (25 yrs):  (0.060128321159388376, 0.77045426823877705)
Nevada Pearson correlation (25 yrs):  (-0.0074098461271704177, 0.97134206784802668)
New Hampshire Pearson correlation (25 yrs):  (0.21748798499864186, 0.28584720260918278)
New Jersey Pearson correlation (25 yrs):  (-0.00015802952922083872, 0.99938869029020183)
New Mexico Pearson correlation (25 yrs):  (0.13944811052229286, 0.49687822924333724)
New York Pearson correlation (25 yrs):  (-0.70881401764272278, 5.0567253176523358e-05)
North Carolina Pearson correlation (25 yrs):  (0.45742492016071012, 0.018796550588318882)
North Dakota Pearson correlation (25 yrs):  (nan, 1.0)
Ohio Pearson correlation (25 yrs):  (0.11597679633615106, 0.57262254151865233)
Oklahoma Pearson correlation (25 yrs):  (0.1219737895704559, 0.55279171886759104)
Oregon Pearson correlation (25 yrs):  (0.52790103006178923, 0.0055744763827537082)
Pennsylvania Pearson correlation (25 yrs):  (0.02787268884846145, 0.8924857694603906)
Rhode Island Pearson correlation (25 yrs):  (nan, 1.0)
South Carolina Pearson correlation (25 yrs):  (-0.16518799926871244, 0.41999240017350492)
South Dakota Pearson correlation (25 yrs):  (0.33499484782488798, 0.094352596318203447)
Tennessee Pearson correlation (25 yrs):  (0.15300200851745555, 0.45554574078013887)
Texas Pearson correlation (25 yrs):  (-0.37050970618696732, 0.062425164566266567)
Utah Pearson correlation (25 yrs):  (-0.017861534768124281, 0.93098650596191235)
Vermont Pearson correlation (25 yrs):  (0.14634908433950014, 0.47560364198763316)
Virginia Pearson correlation (25 yrs):  (0.39650759543134884, 0.0449174234850006)
Washington Pearson correlation (25 yrs):  (-0.097424471168259391, 0.63588029958513248)
West Virginia Pearson correlation (25 yrs):  (0.14944467714060808, 0.46621484173658656)
Wisconsin Pearson correlation (25 yrs):  (0.17522212765285072, 0.39190274682348691)
Wyoming Pearson correlation (25 yrs):  (-0.25156834713032272, 0.2150787619416461)

## Same, with std. err of median household income

In [51]:
filepath5 = '../../raw/economic_stats/census_median_household_income_stderr.csv'
csv5 = pd.read_csv(filepath5)
mhi_se_df = pd.DataFrame(csv5)

In [56]:
mhi_se_df.Year.max()

2016

In [59]:
mhi_se_df = mhi_se_df[mhi_se_df.Year != 2016]
mhi_se_df = mhi_se_df.rename(columns={'D.C.': 'District of Columbia'})

In [60]:
mhi_se_df = mhi_se_df.replace(np.nan, 0)

In [61]:
for element in shootings_percap_df.columns.tolist()[:-1]:
    print(element, 'Pearson correlation (25 yrs): ', pearsonr(shootings_percap_df[element], mhi_se_df[element]))

Alabama Pearson correlation (25 yrs):  (0.31417362466353749, 0.11803627045936879)
Alaska Pearson correlation (25 yrs):  (-0.16887882502832696, 0.40953403411460187)
Arizona Pearson correlation (25 yrs):  (0.36855449206683805, 0.063929374248337473)
Arkansas Pearson correlation (25 yrs):  (-0.15051262252715847, 0.46299831172283112)
California Pearson correlation (25 yrs):  (0.045811992456136645, 0.82413946348569278)
Colorado Pearson correlation (25 yrs):  (0.30701487047499937, 0.12710947989272167)
Connecticut Pearson correlation (25 yrs):  (0.076070921713367809, 0.71186962115637797)
Delaware Pearson correlation (25 yrs):  (-0.13203195595305983, 0.52025823257624126)
District of Columbia Pearson correlation (25 yrs):  (-0.15726762035115333, 0.44292393122579199)
Florida Pearson correlation (25 yrs):  (0.47222179537790326, 0.014858321796077502)
Georgia Pearson correlation (25 yrs):  (0.43491359549542841, 0.02639073218846617)
Hawaii Pearson correlation (25 yrs):  (0.19264896554609739, 0.34574103483259166)
Idaho Pearson correlation (25 yrs):  (-0.041062055351154661, 0.8421356380940721)
Illinois Pearson correlation (25 yrs):  (0.01926183259360971, 0.92559020066893349)
Indiana Pearson correlation (25 yrs):  (0.076692047044202794, 0.70961668163994718)
Iowa Pearson correlation (25 yrs):  (0.056687580009991648, 0.7832730077753679)
Kansas Pearson correlation (25 yrs):  (-0.1800077728703578, 0.37889134782475031)
Kentucky Pearson correlation (25 yrs):  (0.45370904776848053, 0.019909195094652388)
Louisiana Pearson correlation (25 yrs):  (0.30179513780388945, 0.13403802052946828)
Maine Pearson correlation (25 yrs):  (-0.021781277545024551, 0.91588927511013873)
Maryland Pearson correlation (25 yrs):  (-0.019766535405771585, 0.92364600855874157)
Massachusetts Pearson correlation (25 yrs):  (-0.08400027283708135, 0.68329116166902626)
Michigan Pearson correlation (25 yrs):  (0.098073555139791227, 0.63362107987635796)
Minnesota Pearson correlation (25 yrs):  (-0.21595360476311326, 0.28934374559070253)
Mississippi Pearson correlation (25 yrs):  (0.18067370709948394, 0.37710073132486532)
Missouri Pearson correlation (25 yrs):  (0.070063596395330136, 0.73377840033402186)
Montana Pearson correlation (25 yrs):  (-0.047603046924179652, 0.81737556184462146)
Nebraska Pearson correlation (25 yrs):  (0.015624424233638344, 0.939613692137926)
Nevada Pearson correlation (25 yrs):  (0.053464887064119095, 0.79532960800734631)
New Hampshire Pearson correlation (25 yrs):  (0.087162274858053321, 0.6720097405232841)
New Jersey Pearson correlation (25 yrs):  (-0.030670842648053847, 0.88176325756507057)
New Mexico Pearson correlation (25 yrs):  (0.2720995988520819, 0.17870883308115279)
New York Pearson correlation (25 yrs):  (-0.52198576617353665, 0.0062345831008198691)
North Carolina Pearson correlation (25 yrs):  (0.52230637237810484, 0.0061971925552323287)
North Dakota Pearson correlation (25 yrs):  (nan, 1.0)
Ohio Pearson correlation (25 yrs):  (-0.17668000753786869, 0.38791241247933528)
Oklahoma Pearson correlation (25 yrs):  (0.049915678018036792, 0.80866078794785112)
Oregon Pearson correlation (25 yrs):  (0.38978392096970443, 0.049020189477458703)
Pennsylvania Pearson correlation (25 yrs):  (-0.018981507280909572, 0.92667023686631989)
Rhode Island Pearson correlation (25 yrs):  (nan, 1.0)
South Carolina Pearson correlation (25 yrs):  (-0.12520292373948655, 0.54224602095970331)
South Dakota Pearson correlation (25 yrs):  (0.34314077795200099, 0.08612892644888151)
Tennessee Pearson correlation (25 yrs):  (0.077199239712829895, 0.70777875731413942)
Texas Pearson correlation (25 yrs):  (-0.18679979715245698, 0.36085867822077278)
Utah Pearson correlation (25 yrs):  (-0.15031596122339683, 0.46358976184269896)
Vermont Pearson correlation (25 yrs):  (-0.093823050902112112, 0.64847271626372127)
Virginia Pearson correlation (25 yrs):  (0.13527432962422414, 0.5099715474236064)
Washington Pearson correlation (25 yrs):  (-0.062444929465513645, 0.76185628925461346)
West Virginia Pearson correlation (25 yrs):  (-0.046814448786785645, 0.82035215751477097)
Wisconsin Pearson correlation (25 yrs):  (-0.18260351013489756, 0.37193937981860936)
Wyoming Pearson correlation (25 yrs):  (-0.12825721578582475, 0.5323585913076162)

# Lets check violent crime too just in case

In [62]:
filepath6 = '../../raw/ucr_violent_crime_rate_by_state.csv'
csv6 = pd.read_csv('../../raw/ucr_violent_crime_rate_by_state.csv')
vc_df = pd.DataFrame(csv6)

In [63]:
vc_df.Year.max()

2014

### have to cut down other dataframes to fit, this one is a year shorter, both start at 1990

In [87]:
for element in shootings_percap_df.columns.tolist()[:-1]:
    print(element, 'Pearson correlation (24 yrs): ', pearsonr(shootings_percap_df[element][:-1], vc_df[element]))

Alabama Pearson correlation (24 yrs):  (-0.20136348331058504, 0.33444082251139151)
Alaska Pearson correlation (24 yrs):  (0.18356829981418732, 0.37975410600063542)
Arizona Pearson correlation (24 yrs):  (-0.18191455881111457, 0.38413607778783099)
Arkansas Pearson correlation (24 yrs):  (-0.068116105143850067, 0.74630141381820447)
California Pearson correlation (24 yrs):  (0.11080307287987391, 0.59799904236790691)
Colorado Pearson correlation (24 yrs):  (-0.26318143893441714, 0.20369725726817958)
Connecticut Pearson correlation (24 yrs):  (-0.15408229411949098, 0.46210919657648764)
Delaware Pearson correlation (24 yrs):  (0.13799747968891082, 0.51065301293778642)
District of Columbia Pearson correlation (24 yrs):  (0.21904974403031605, 0.29279011251716847)
Florida Pearson correlation (24 yrs):  (-0.1312788361914406, 0.53163921979829076)
Georgia Pearson correlation (24 yrs):  (-0.034122846484193232, 0.87136400368031586)
Hawaii Pearson correlation (24 yrs):  (-0.15250402310581126, 0.46676323714282775)
Idaho Pearson correlation (24 yrs):  (-0.064297306261461892, 0.76010443780145565)
Illinois Pearson correlation (24 yrs):  (-0.1779930503712488, 0.39464167431360464)
Indiana Pearson correlation (24 yrs):  (-0.08202685994173331, 0.69668818921363762)
Iowa Pearson correlation (24 yrs):  (0.10499667656107453, 0.61743382458652851)
Kansas Pearson correlation (24 yrs):  (0.042653804632795542, 0.83957105820509803)
Kentucky Pearson correlation (24 yrs):  (-0.010110385919457811, 0.96174420385997128)
Louisiana Pearson correlation (24 yrs):  (-0.20233982126945446, 0.3320530274334812)
Maine Pearson correlation (24 yrs):  (-0.041379885713201871, 0.84430440681141483)
Maryland Pearson correlation (24 yrs):  (-0.26669219214899237, 0.19750827614661418)
Massachusetts Pearson correlation (24 yrs):  (0.33328972452419586, 0.10350998141066142)
Michigan Pearson correlation (24 yrs):  (-0.049172975701004248, 0.81543653552423501)
Minnesota Pearson correlation (24 yrs):  (0.16067588739793234, 0.44292998146099738)
Mississippi Pearson correlation (24 yrs):  (0.030178761540594363, 0.8861315806296397)
Missouri Pearson correlation (24 yrs):  (0.26078652508192396, 0.20799392552864698)
Montana Pearson correlation (24 yrs):  (-0.21428884240355889, 0.30366711769791643)
Nebraska Pearson correlation (24 yrs):  (-0.15760943391055454, 0.45179625428545844)
Nevada Pearson correlation (24 yrs):  (-0.18885388233574579, 0.36594236009951675)
New Hampshire Pearson correlation (24 yrs):  (0.38000338058402533, 0.060967367778403329)
New Jersey Pearson correlation (24 yrs):  (-0.078264577388356321, 0.70999720833065028)
New Mexico Pearson correlation (24 yrs):  (-0.039588026579423313, 0.85097105680287199)
New York Pearson correlation (24 yrs):  (0.77881352797680237, 4.5235682658630204e-06)
North Carolina Pearson correlation (24 yrs):  (-0.34547227292599292, 0.09074863665664315)
North Dakota Pearson correlation (24 yrs):  (nan, 1.0)
Ohio Pearson correlation (24 yrs):  (-0.065725812605780851, 0.75493251251639837)
Oklahoma Pearson correlation (24 yrs):  (-0.17686301659910988, 0.39769879795631102)
Oregon Pearson correlation (24 yrs):  (-0.29368863867371864, 0.15418261166418415)
Pennsylvania Pearson correlation (24 yrs):  (0.091876871143823716, 0.66226257690382462)
Rhode Island Pearson correlation (24 yrs):  (nan, 1.0)
South Carolina Pearson correlation (24 yrs):  (0.1278887251634015, 0.54238091272980404)
South Dakota Pearson correlation (24 yrs):  (nan, 1.0)
Tennessee Pearson correlation (24 yrs):  (-0.085309640818527849, 0.68514598971878593)
Texas Pearson correlation (24 yrs):  (0.47520302134292142, 0.016367305741714366)
Utah Pearson correlation (24 yrs):  (-0.052730228549783965, 0.8023344227767899)
Vermont Pearson correlation (24 yrs):  (0.37097672647403984, 0.067896112660310079)
Virginia Pearson correlation (24 yrs):  (-0.44743024713173191, 0.024919135234528135)
Washington Pearson correlation (24 yrs):  (0.044658371993102075, 0.83213393648891043)
West Virginia Pearson correlation (24 yrs):  (0.086702071083868265, 0.68027069043348587)
Wisconsin Pearson correlation (24 yrs):  (-0.057914946700536082, 0.78333141231806047)
Wyoming Pearson correlation (24 yrs):  (0.22542348030557754, 0.27861560469996022)

/anaconda/lib/python3.6/site-packages/scipy/stats/stats.py:3003: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den

# Lets do homicide as well

In [79]:
filepath7 = '../../raw/additional_crime_stats/ucr_violent_crime_total.csv'
csv7 = pd.read_csv(filepath7)
homicide_df = pd.DataFrame(csv7)

### For this one, since it is total violent crime rather than a rate, we will use the shootings_df, rather than the per_capita

In [82]:
homicide_df.Year.max()

2014

In [86]:
for element in shootings_df.columns.tolist()[1:]:
    print(element, 'Pearson correlation (24 yrs): ', pearsonr(shootings_df[element][:-1], homicide_df[element]))

Alabama Pearson correlation (24 yrs):  (-0.188898309266568, 0.36582752331208679)
Alaska Pearson correlation (24 yrs):  (0.0374456466662203, 0.85895485459391319)
Arizona Pearson correlation (24 yrs):  (-0.057353773134906985, 0.78538261891220307)
Arkansas Pearson correlation (24 yrs):  (-0.079916698068750389, 0.70414241925591003)
California Pearson correlation (24 yrs):  (0.0095502073192207694, 0.96386242150591306)
Colorado Pearson correlation (24 yrs):  (-0.11370137451939875, 0.58839616902466751)
Connecticut Pearson correlation (24 yrs):  (-0.15737639898275957, 0.45247385032628373)
Delaware Pearson correlation (24 yrs):  (0.23979242106977225, 0.24828643302258729)
District of Columbia Pearson correlation (24 yrs):  (0.16628767630413455, 0.42694737069364819)
Florida Pearson correlation (24 yrs):  (-0.24759385080342877, 0.23275961680928139)
Georgia Pearson correlation (24 yrs):  (-0.13798538010668832, 0.51069044004698971)
Hawaii Pearson correlation (24 yrs):  (0.14317901639594807, 0.49474910230783131)
Idaho Pearson correlation (24 yrs):  (-0.22184519675797798, 0.28651872066835082)
Illinois Pearson correlation (24 yrs):  (-0.21216712493087736, 0.3085941016977245)
Indiana Pearson correlation (24 yrs):  (-0.0056430533404295295, 0.97864248970439605)
Iowa Pearson correlation (24 yrs):  (0.11270037731576102, 0.59170523016040311)
Kansas Pearson correlation (24 yrs):  (-0.062889189781102459, 0.76521235549093292)
Kentucky Pearson correlation (24 yrs):  (-0.037698138633499689, 0.85801320217774246)
Louisiana Pearson correlation (24 yrs):  (-0.19896819188424703, 0.34034249994516408)
Maine Pearson correlation (24 yrs):  (0.028599916058612947, 0.89205378188928697)
Maryland Pearson correlation (24 yrs):  (-0.26059373128234231, 0.20834245855869632)
Massachusetts Pearson correlation (24 yrs):  (0.33514534530585366, 0.101484885426357)
Michigan Pearson correlation (24 yrs):  (-0.064309648768743788, 0.76005970835974568)
Minnesota Pearson correlation (24 yrs):  (0.19168803262440592, 0.35865860809060923)
Mississippi Pearson correlation (24 yrs):  (0.022716148545975399, 0.91417068528175804)
Missouri Pearson correlation (24 yrs):  (0.25134554806425941, 0.22552691242306769)
Montana Pearson correlation (24 yrs):  (-0.22281730278288756, 0.28435786425776827)
Nebraska Pearson correlation (24 yrs):  (-0.18440256278173756, 0.37755446102413481)
Nevada Pearson correlation (24 yrs):  (0.014177110502008672, 0.94637501897410925)
New Hampshire Pearson correlation (24 yrs):  (0.36979192934402755, 0.068848619714606568)
New Jersey Pearson correlation (24 yrs):  (-0.068501479372348295, 0.74491261324899438)
New Mexico Pearson correlation (24 yrs):  (0.0098128850204031656, 0.96286912112081491)
New York Pearson correlation (24 yrs):  (0.77335045120791246, 5.8166028577575863e-06)
North Carolina Pearson correlation (24 yrs):  (-0.41998647485372753, 0.036600293273238195)
Ohio Pearson correlation (24 yrs):  (-0.072148052448699429, 0.73181002856303401)
Oklahoma Pearson correlation (24 yrs):  (-0.21860813043444868, 0.29378864177128383)
Oregon Pearson correlation (24 yrs):  (-0.27126925156595572, 0.18963408361359815)
Pennsylvania Pearson correlation (24 yrs):  (0.1219568127702903, 0.56141559203560698)
South Carolina Pearson correlation (24 yrs):  (0.079427706753914182, 0.7058736213275647)
South Dakota Pearson correlation (24 yrs):  (nan, 1.0)
Tennessee Pearson correlation (24 yrs):  (0.1985057874113039, 0.34148892690256949)
Texas Pearson correlation (24 yrs):  (0.39232324812791081, 0.052407741090484426)
Utah Pearson correlation (24 yrs):  (-0.1859625796719776, 0.37346098448825282)
Vermont Pearson correlation (24 yrs):  (0.37043795295245424, 0.068327993685586702)
Virginia Pearson correlation (24 yrs):  (-0.4543724522079966, 0.022502575622451101)
Washington Pearson correlation (24 yrs):  (0.027409393203933728, 0.89652313196301259)
West Virginia Pearson correlation (24 yrs):  (0.082114600902621709, 0.69637882621539515)
Wisconsin Pearson correlation (24 yrs):  (0.029958452238689679, 0.88695760516425692)
Wyoming Pearson correlation (24 yrs):  (0.17756949500602873, 0.3957859775455117)

/anaconda/lib/python3.6/site-packages/scipy/stats/stats.py:3003: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den